name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: github - publish - list
        run: |
          git config user.name "${{ secrets.GIT_USER }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add .
          git status
          git commit -m "Updated list"
          git push          